name: CI

on: [push]

env:
  node_version: "20.x"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node_version }}
        cache: "npm"
    - name: Install JS dependencies
      run: npm install
    - name: Lint
      run: npm run lint
